spring.application.name=discovery-service
server.port=8761
#Eureka-Client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#Eureka-Server
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=30000
#Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
#Logging
logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG
#Security
spring.security.user.name=eureka
spring.security.user.password=eureka123